"""empty message

Revision ID: 6f3436c723fe
Revises: 
Create Date: 2017-05-19 14:31:21.697707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3436c723fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UEA_ALUNO',
    sa.Column('alu_matricula', sa.String(length=10), nullable=False),
    sa.Column('alu_nome', sa.String(length=50), nullable=True),
    sa.Column('alu_endereco', sa.String(length=100), nullable=True),
    sa.Column('alu_bairro', sa.String(length=50), nullable=True),
    sa.Column('alu_cidade', sa.String(length=50), nullable=True),
    sa.Column('alu_UF', sa.String(length=2), nullable=True),
    sa.Column('alu_CEP', sa.String(length=8), nullable=True),
    sa.Column('alu_email', sa.String(length=50), nullable=True),
    sa.Column('alu_telefone', sa.String(length=15), nullable=True),
    sa.Column('alu_celular', sa.String(length=15), nullable=True),
    sa.Column('alu_senha', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('alu_matricula'),
    sa.UniqueConstraint('alu_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UEA_ALUNO')
    # ### end Alembic commands ###
